In [4]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [5]:
df = pd.read_csv("../testing/collected_data_supertest.csv"); df

,style,algorithm,growth,PS,num_alts,force_chance,seed,range,width,seconds,depth,evaluated,expanded,intractable
0,Berliner,prefer-DR,1.00,yes,2,0.0,28,100,3,0.320,1,4,1,no
1,Berliner,prefer-DR,1.00,yes,2,0.0,5,100,3,0.400,12,166,55,no
2,Berliner,prefer-DR,1.00,yes,2,0.0,17,100,3,0.336,7,70,23,no
3,Berliner,prefer-DR,1.00,yes,2,0.0,19,100,3,0.335,8,64,21,no
4,Berliner,prefer-DR,1.00,yes,2,0.0,26,100,3,0.332,5,52,17,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110921,BaseRulesBefore,always-PB,0.75,no,5,0.0,27750,100,7,0.037,8,890,127,no
110922,BaseRulesBefore,alternate,0.75,no,5,0.0,27748,100,7,0.025,6,638,91,no
110923,BaseRulesBefore,alternate,0.75,no,5,0.0,27750,100,7,0.026,7,666,95,no
110924,BaseRulesBefore,randomize,0.75,no,5,0.0,27748,100,7,0.018,6,638,91,no
110925,BaseRulesBefore,randomize,0.75,no,5,0.0,27750,100,7,0.022,7,666,95,no

In [3]:
import csv

""" write the indices which are fully completed runs to a file so we can skip them in the next set of runs """

seed_counts = df.groupby(["seed"]).algorithm.count()

with open("completed_indices.csv","w") as f:
    wr = csv.writer(f,delimiter="\n")
    wr.writerow(list(seed_counts[seed_counts == 4].index))

In [4]:
per_tree = df.groupby(["style","range"])

In [5]:
per_tree['expanded'].max() + 1

style            range
BaseRulesBefore  100      4002
                 200      4002
                 400      4002
                 800      4002
                 1600     4002
                 3200     4002
                 6400     4002
                 12800    4002
Berliner         100      4002
                 200      4002
                 400      4002
                 800      4002
                 1600     4002
                 3200     4002
                 6400     4002
                 12800    4002
BerlinerSplit    100        39
                 200        51
                 400        35
                 800        38
                 1600       25
                 3200       38
                 6400       48
                 12800      40
Legacy           100      4002
                 200      4002
                 400      4002
                 800      4002
                 1600     4002
                 3200     4002
                 6400     4002
                 12800    4002
Palay            100      4002
                 200      4002
                 400      4002
                 800      4002
                 1600     4002
                 3200     4002
                 6400     4002
                 12800    4002
Name: expanded, dtype: int64

In [6]:
df

,style,algorithm,growth,PS,num_alts,force_chance,seed,range,width,seconds,depth,evaluated,expanded,intractable
0,Berliner,prefer-DR,1.00,yes,2,0.0,28,100,3,0.320,1,4,1,no
1,Berliner,prefer-DR,1.00,yes,2,0.0,5,100,3,0.400,12,166,55,no
2,Berliner,prefer-DR,1.00,yes,2,0.0,17,100,3,0.336,7,70,23,no
3,Berliner,prefer-DR,1.00,yes,2,0.0,19,100,3,0.335,8,64,21,no
4,Berliner,prefer-DR,1.00,yes,2,0.0,26,100,3,0.332,5,52,17,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110921,BaseRulesBefore,always-PB,0.75,no,5,0.0,27750,100,7,0.037,8,890,127,no
110922,BaseRulesBefore,alternate,0.75,no,5,0.0,27748,100,7,0.025,6,638,91,no
110923,BaseRulesBefore,alternate,0.75,no,5,0.0,27750,100,7,0.026,7,666,95,no
110924,BaseRulesBefore,randomize,0.75,no,5,0.0,27748,100,7,0.018,6,638,91,no
110925,BaseRulesBefore,randomize,0.75,no,5,0.0,27750,100,7,0.022,7,666,95,no

In [7]:
df.groupby(["style","algorithm"]).intractable.apply(lambda x : x[x.str.contains("yes")].count())

style            algorithm
BaseRulesBefore  alternate     111
                 always-PB     341
                 prefer-DR     311
                 randomize     117
Berliner         alternate    1671
                 always-PB    2415
                 prefer-DR    2345
                 randomize    1654
BerlinerSplit    alternate       0
                 always-PB       0
                 prefer-DR       0
                 randomize       0
Legacy           alternate     534
                 always-PB     597
                 prefer-DR     668
                 randomize     535
Palay            alternate    1550
                 always-PB    1952
                 prefer-DR    1956
                 randomize    1540
Name: intractable, dtype: int64

In [37]:
df[df.intractable == 'no'].corr()['seconds']

growth          0.084481
num_alts        0.255515
force_chance         NaN
seed           -0.102745
range           0.055722
width           0.002051
seconds         1.000000
depth           0.580855
evaluated       0.771753
expanded        0.880742
Name: seconds, dtype: float64

In [38]:
df[df.num_alts == 8].groupby(['style','algorithm']).intractable.apply(lambda x : x[x.str.contains("yes")].count() / x.count())

style            algorithm
BaseRulesBefore  alternate    0.063728
                 always-PB    0.184570
                 prefer-DR    0.170301
                 randomize    0.065672
Berliner         alternate    0.890000
                 always-PB    0.996250
                 prefer-DR    0.995625
                 randomize    0.881875
Legacy           alternate    0.328125
                 always-PB    0.365000
                 prefer-DR    0.410625
                 randomize    0.328750
Palay            alternate    0.900625
                 always-PB    0.997500
                 prefer-DR    0.995625
                 randomize    0.895625
Name: intractable, dtype: float64

In [10]:
df[df.intractable == "no"].evaluated.quantile(0.975)

14098.400000000023

In [11]:
df[df.intractable == "no"].expanded.quantile(0.975)

2253.300000000003

In [12]:
df[df.intractable == "no"].depth.quantile(0.975)

23.0

In [13]:
df[(df.depth >= 10) & (df.depth < 150)].seconds.mean()

37.2635800764532

In [14]:
df[(df.evaluated < 14000) & (df.evaluated >= 100)].seconds.mean()

7.8689529736582395

In [15]:
df.groupby(["num_alts","force_chance","width"]).seconds.mean()

num_alts  force_chance  width
2         0.0           3         0.001624
                        5         0.000272
                        7         0.000234
                        9         0.000217
3         0.0           3         0.018336
                        5         0.015991
                        7         0.016247
                        9         0.019622
5         0.0           3         6.885913
                        5         8.896696
                        7         9.859015
                        9         8.931135
8         0.0           3        40.552389
                        5        39.226693
                        7        51.915592
                        9        38.921632
Name: seconds, dtype: float64

In [16]:
df.growth.unique()

array([1.  , 0.75])

In [17]:
df2 = pd.read_csv("collected_data_supertest_numalt23.csv"); df2

,style,algorithm,growth,PS,num_alts,force_chance,seed,range,width,seconds,depth,evaluated,expanded,intractable
0,Berliner,prefer-DR,1.0,yes,2,0.0,4,100,3,0.166,1,4,1,no
1,Berliner,prefer-DR,1.0,yes,2,0.0,17,100,3,0.265,7,70,23,no
2,Berliner,prefer-DR,1.0,yes,2,0.0,19,100,3,0.265,8,64,21,no
3,Berliner,prefer-DR,1.0,yes,2,0.0,18,100,3,0.264,10,64,21,no
4,Berliner,prefer-DR,1.0,yes,2,0.0,26,100,3,0.262,5,52,17,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1107195,BaseRulesAfter,alternate,4.0,no,3,1.0,546271,100,9,9.192,44,30007,3334,yes
1107196,BaseRulesAfter,randomize,4.0,no,3,1.0,546271,100,9,0.049,13,2530,281,no
1107197,BaseRulesBefore,randomize,4.0,no,3,1.0,534299,200,9,8.026,61,30007,3334,yes
1107198,BaseRulesAfter,randomize,4.0,yes,3,1.0,541488,400,9,5.995,95,30007,3334,yes
1107199,BaseRulesAfter,randomize,4.0,no,3,1.0,547096,200,9,7.262,42,30007,3334,yes

In [63]:
df2[(df2.algorithm == "prefer-DR")].groupby(["style","growth","num_alts","force_chance"]).evaluated.quantile(0.9)[:50]

style            growth  num_alts  force_chance
BaseRulesAfter   0.75    2         0.00              71.0
                                   0.33              73.0
                                   0.67              73.0
                                   1.00              82.0
                         3         0.00             217.0
                                   0.33             244.0
                                   0.67             262.0
                                   1.00             253.0
                 1.00    2         0.00              91.0
                                   0.33              92.0
                                   0.67              92.0
                                   1.00              92.0
                         3         0.00             365.0
                                   0.33             379.0
                                   0.67             370.0
                                   1.00             361.0
                 1.40    2         0.00             113.0
                                   0.33             116.0
                                   0.67             109.0
                                   1.00             109.0
                         3         0.00             739.0
                                   0.33             703.5
                                   0.67             649.0
                                   1.00             622.0
                 2.00    2         0.00             145.0
                                   0.33             134.0
                                   0.67             127.0
                                   1.00             127.0
                         3         0.00            1054.0
                                   0.33            1009.0
                                   0.67             973.0
                                   1.00             883.0
                 4.00    2         0.00             113.0
                                   0.33             141.0
                                   0.67             155.0
                                   1.00             162.0
                         3         0.00             298.0
                                   0.33             388.0
                                   0.67             519.0
                                   1.00             685.0
BaseRulesBefore  0.75    2         0.00              73.0
                                   0.33              76.0
                                   0.67              78.0
                                   1.00              78.0
                         3         0.00             262.0
                                   0.33             280.0
                                   0.67             298.3
                                   1.00             316.0
                 1.00    2         0.00              92.0
                                   0.33              85.0
Name: evaluated, dtype: float64

In [64]:
df2[(df2.algorithm == "prefer-DR")].groupby(["style","growth","num_alts","force_chance"]).evaluated.quantile(0.9)[:50]

style            growth  num_alts  force_chance
BaseRulesAfter   0.75    2         0.00              71.0
                                   0.33              73.0
                                   0.67              73.0
                                   1.00              82.0
                         3         0.00             217.0
                                   0.33             244.0
                                   0.67             262.0
                                   1.00             253.0
                 1.00    2         0.00              91.0
                                   0.33              92.0
                                   0.67              92.0
                                   1.00              92.0
                         3         0.00             365.0
                                   0.33             379.0
                                   0.67             370.0
                                   1.00             361.0
                 1.40    2         0.00             113.0
                                   0.33             116.0
                                   0.67             109.0
                                   1.00             109.0
                         3         0.00             739.0
                                   0.33             703.5
                                   0.67             649.0
                                   1.00             622.0
                 2.00    2         0.00             145.0
                                   0.33             134.0
                                   0.67             127.0
                                   1.00             127.0
                         3         0.00            1054.0
                                   0.33            1009.0
                                   0.67             973.0
                                   1.00             883.0
                 4.00    2         0.00             113.0
                                   0.33             141.0
                                   0.67             155.0
                                   1.00             162.0
                         3         0.00             298.0
                                   0.33             388.0
                                   0.67             519.0
                                   1.00             685.0
BaseRulesBefore  0.75    2         0.00              73.0
                                   0.33              76.0
                                   0.67              78.0
                                   1.00              78.0
                         3         0.00             262.0
                                   0.33             280.0
                                   0.67             298.3
                                   1.00             316.0
                 1.00    2         0.00              92.0
                                   0.33              85.0
Name: evaluated, dtype: float64

In [28]:
g2 = df2.groupby(["style","algorithm","num_alts"])
count_intractable = g2.intractable.apply(lambda x : x[x.str.contains("yes")].count())
count = g2.intractable.count()
evals = g2.evaluated.quantile(0.9)
pd.DataFrame({"num-intractable": count_intractable, "num": count, "90th%-evaluations": pd.Series(evals, dtype='int')})

                                    num-intractable    num  90th%-evaluations
style           algorithm num_alts
BaseRulesAfter  alternate 2                       0  64000                 91
                          3                     151  64000                321
                always-PB 2                       0  64000                100
                          3                     581  64000                478
                prefer-DR 2                       0  64000                109
                          3                     472  64000                498
                randomize 2                       0  64000                 91
                          3                     179  64000                325
BaseRulesBefore alternate 2                       0  64000                 91
                          3                     463  64000                554
                always-PB 2                       0  64000                106
                          3                    2161  64000               1226
                prefer-DR 2                       0  64000                113
                          3                    1763  64000               1163
                randomize 2                       0  64000                 91
                          3                     587  64000                575
Berliner        alternate 2                       0   1600                115
                          3                      11   1600                541
                always-PB 2                       0   1600                121
                          3                      51   1600                838
                prefer-DR 2                       0   1600                136
                          3                      49   1600                910
                randomize 2                       0   1600                118
                          3                       9   1600                547
BerlinerSplit   alternate 2                       0   1600                 82
                always-PB 2                       0   1600                 85
                prefer-DR 2                       0   1600                 92
                randomize 2                       0   1600                 82
Legacy          alternate 2                       0   6400                106
                          3                       0   6400                334
                always-PB 2                       0   6400                126
                          3                       0   6400                397
                prefer-DR 2                       0   6400                134
                          3                       0   6400                456
                randomize 2                       0   6400                106
                          3                       0   6400                334
Palay           alternate 2                       0   1600                111
                          3                       0   1600                622
                always-PB 2                       0   1600                126
                          3                       0   1600                790
                prefer-DR 2                       0   1600                127
                          3                       0   1600                861
                randomize 2                       0   1600                113
                          3                       0   1600                611

In [29]:
df2

,style,algorithm,growth,PS,num_alts,force_chance,seed,range,width,seconds,depth,evaluated,expanded,intractable
0,Berliner,prefer-DR,1.0,yes,2,0.0,4,100,3,0.166,1,4,1,no
1,Berliner,prefer-DR,1.0,yes,2,0.0,17,100,3,0.265,7,70,23,no
2,Berliner,prefer-DR,1.0,yes,2,0.0,19,100,3,0.265,8,64,21,no
3,Berliner,prefer-DR,1.0,yes,2,0.0,18,100,3,0.264,10,64,21,no
4,Berliner,prefer-DR,1.0,yes,2,0.0,26,100,3,0.262,5,52,17,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1107195,BaseRulesAfter,alternate,4.0,no,3,1.0,546271,100,9,9.192,44,30007,3334,yes
1107196,BaseRulesAfter,randomize,4.0,no,3,1.0,546271,100,9,0.049,13,2530,281,no
1107197,BaseRulesBefore,randomize,4.0,no,3,1.0,534299,200,9,8.026,61,30007,3334,yes
1107198,BaseRulesAfter,randomize,4.0,yes,3,1.0,541488,400,9,5.995,95,30007,3334,yes
1107199,BaseRulesAfter,randomize,4.0,no,3,1.0,547096,200,9,7.262,42,30007,3334,yes

In [35]:
df2[df2.intractable == "yes"].groupby(["num_alts","force_chance","algorithm"]).depth.max()

num_alts  force_chance  algorithm
3         0.00          alternate    1001
                        always-PB    1001
                        prefer-DR    1001
                        randomize    1001
          0.33          alternate    1001
                        always-PB    1001
                        prefer-DR    1001
                        randomize    1001
          0.67          alternate    1001
                        always-PB    1001
                        prefer-DR    1001
                        randomize    1001
          1.00          alternate    1001
                        always-PB    1001
                        prefer-DR    1001
                        randomize    1001
Name: depth, dtype: int64

In [33]:
df[df.intractable == "no"].groupby(["num_alts","force_chance","algorithm"]).depth.max()

num_alts  force_chance  algorithm
2         0.0           alternate     12
                        always-PB     16
                        prefer-DR     18
                        randomize     13
3         0.0           alternate     22
                        always-PB     29
                        prefer-DR     25
                        randomize     22
5         0.0           alternate    137
                        always-PB    137
                        prefer-DR    124
                        randomize     57
8         0.0           alternate     58
                        always-PB     82
                        prefer-DR     59
                        randomize     82
Name: depth, dtype: int64

In [65]:
dfb = pd.read_csv("collected_data_berlinersplit.csv"); dfb

,style,algorithm,growth,PS,num_alts,force_chance,seed,range,width,seconds,depth,evaluated,expanded,intractable
0,BerlinerSplit,prefer-DR,1.0,yes,2,0.0,12801,100,3,0.071,2,13,4,no
1,BerlinerSplit,prefer-DR,1.0,yes,2,0.0,12804,100,3,0.122,8,148,49,no
2,BerlinerSplit,prefer-DR,1.0,yes,2,0.0,12808,100,3,0.104,9,82,27,no
3,BerlinerSplit,prefer-DR,1.0,yes,2,0.0,12819,100,3,0.097,7,67,22,no
4,BerlinerSplit,prefer-DR,1.0,yes,2,0.0,12817,100,3,0.094,8,55,18,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,BerlinerSplit,alternate,1.0,yes,2,0.0,14353,12800,9,0.083,11,2890,321,no
6396,BerlinerSplit,randomize,1.0,yes,2,0.0,14353,12800,9,0.082,12,2971,330,no
6397,BerlinerSplit,always-PB,1.0,yes,2,0.0,14300,12800,5,0.822,1001,10231,2046,yes
6398,BerlinerSplit,alternate,1.0,yes,2,0.0,14300,12800,5,0.718,1001,10321,2064,yes
6399,BerlinerSplit,randomize,1.0,yes,2,0.0,14300,12800,5,0.706,1001,10231,2046,yes

In [66]:
dfb.sort_values("seconds")

,style,algorithm,growth,PS,num_alts,force_chance,seed,range,width,seconds,depth,evaluated,expanded,intractable
4849,BerlinerSplit,alternate,1.0,yes,2,0.0,14035,6400,3,0.000,3,19,6,no
4886,BerlinerSplit,randomize,1.0,yes,2,0.0,14044,6400,3,0.000,5,58,19,no
5543,BerlinerSplit,alternate,1.0,yes,2,0.0,14210,12800,3,0.000,3,22,7,no
5544,BerlinerSplit,randomize,1.0,yes,2,0.0,14210,12800,3,0.000,3,19,6,no
5546,BerlinerSplit,always-PB,1.0,yes,2,0.0,14211,12800,3,0.000,4,25,8,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,BerlinerSplit,prefer-DR,1.0,yes,2,0.0,13651,1600,5,7.778,1001,10651,2130,yes
179,BerlinerSplit,prefer-DR,1.0,yes,2,0.0,12834,100,3,7.816,1001,6670,2223,yes
180,BerlinerSplit,prefer-DR,1.0,yes,2,0.0,12820,100,3,8.156,1001,6760,2253,yes
3337,BerlinerSplit,always-PB,1.0,yes,2,0.0,13489,800,5,8.219,1001,10771,2154,yes
3751,BerlinerSplit,prefer-DR,1.0,yes,2,0.0,13695,1600,5,8.785,1001,11091,2218,yes

In [76]:
dfb[dfb.intractable == "yes"].groupby(["algorithm"]).intractable.count()

algorithm
alternate    171
always-PB    521
prefer-DR    452
randomize    200
Name: intractable, dtype: int64